Running tests on a test flinger device
Loading environment variables
Using environment file: tf_snapd_cm3_refresh
Deleting test flinger data
Creating job for snapd using a device
Running testflinger client
Submitting job to testflinger
JOB_ID: 72f02474-a72d-445c-9470-ecea60f7e3fb
Print job: /var/snap/testflinger-cli/current/job.yaml 
job_queue: dragonboard
global_timeout: 36000
provision_data:
    channel: stable
test_data:
    test_cmds: |
        #!/bin/bash
        sudo apt update || ps aux | grep apt
        sudo apt install -y git curl sshpass
        git clone https://github.com/sergiocazzolato/snappy-qa-jobs.git
        (cd snappy-qa-jobs && git checkout master)
        git clone https://git.launchpad.net/snapd-vendor snapd
        (cd snapd && git checkout master)
        . snapd/tests/lib/external/prepare-ssh.sh "{device_ip}" "22" "ubuntu"
        . snappy-qa-jobs/scripts/utils/register_device.sh "{device_ip}" "22" "test" "ubuntu" "sergiocazzolato@yahoo.com.ar"
        . snappy-qa-jobs/scripts/utils/refresh_core.sh "{device_ip}" "22" "test" "ubuntu" "stable" "edge"
        . snappy-qa-jobs/scripts/utils/run_setup.sh "{device_ip}" "22" "test" "ubuntu" ""
        . snappy-qa-jobs/scripts/utils/get_spread.sh
        . snappy-qa-jobs/scripts/utils/run_spread.sh "{device_ip}" "22" "snapd" "external:ubuntu-core-16-arm-64:tests/" "" "tests/main/auto-refresh" "-v"
Showing job data
This job is currently waiting on a node to become available. You will see no further output until the job starts running.
*******************************************

* Starting setup phase on dragonboard-002 *

*******************************************

Cleaning up container if it exists...
Error response from daemon: No such container: dragonboard002

***********************************************
* Starting provision phase on dragonboard-002 *

***********************************************
Install python-logstash if you want to use logstash logging
2018-03-21 04:41:42,616 dragonboard_002 INFO: BEGIN provision
2018-03-21 04:41:42,616 dragonboard_002 INFO: Booting Master Image
2018-03-21 04:41:42,616 dragonboard_002 INFO: Making sure the master image is booted
2018-03-21 04:41:42,616 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:41:45,619 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:41:48,619 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:41:48,620 dragonboard_002 WARNING: Device is in an unknown state, attempting to recover
2018-03-21 04:41:48,620 dragonboard_002 INFO: Running snmpset -c private -v1 10.101.48.13 .1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2 i 2
iso.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2 = INTEGER: 2
2018-03-21 04:41:48,739 dragonboard_002 INFO: Running sleep 10
2018-03-21 04:41:58,761 dragonboard_002 INFO: Running snmpset -c private -v1 10.101.48.13 .1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2 i 1
iso.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2 = INTEGER: 1
2018-03-21 04:42:08,890 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:42:11,899 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:42:11,900 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:42:24,910 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:42:27,919 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:42:27,920 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:42:40,920 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:42:43,927 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:42:43,928 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:42:56,927 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:42:59,935 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:42:59,936 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:43:12,945 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:43:15,955 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:43:15,956 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:43:28,962 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:43:31,966 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:43:31,967 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:43:44,977 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:43:47,987 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:43:47,988 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:44:00,990 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:44:03,994 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:44:03,994 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:44:17,005 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:44:20,015 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:44:20,016 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:44:33,022 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:44:36,031 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:44:36,032 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:44:49,038 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:44:52,047 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:44:52,047 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:45:05,051 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:45:08,059 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:45:08,060 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:45:21,069 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:45:24,079 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:45:24,080 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:45:37,089 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:45:40,099 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:45:40,100 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:45:53,109 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:45:56,119 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:45:56,120 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:46:09,129 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:46:12,139 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:46:12,140 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:46:25,150 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:46:28,159 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:46:28,160 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:46:41,170 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:46:44,179 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:46:44,180 dragonboard_002 INFO: Checking if test image booted.
2018-03-21 04:46:57,190 dragonboard_002 INFO: Checking if master image booted.
2018-03-21 04:47:00,199 dragonboard_002 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:47:00,200 dragonboard_002 INFO: Checking if test image booted.


            There was an unrecoverable error while running this stage. Your job
            has been automatically resubmitted back to the queue.
            Resubmitting job: 72f02474-a72d-445c-9470-ecea60f7e3fb

*******************************************

* Starting setup phase on dragonboard-003 *

*******************************************

Cleaning up container if it exists...
Error response from daemon: No such container: dragonboard003

***********************************************

* Starting provision phase on dragonboard-003 *

***********************************************
Install python-logstash if you want to use logstash logging
2018-03-21 04:47:10,688 dragonboard_003 INFO: BEGIN provision
2018-03-21 04:47:10,688 dragonboard_003 INFO: Booting Master Image
2018-03-21 04:47:10,688 dragonboard_003 INFO: Making sure the master image is booted
2018-03-21 04:47:10,688 dragonboard_003 INFO: Checking if test image booted.
2018-03-21 04:47:11,791 dragonboard_003 INFO: Running ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@10.101.51.13 sudo sgdisk -o /dev/mmcblk1
Warning: Permanently added '10.101.51.13' (ECDSA) to the list of known hosts.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
2018-03-21 04:47:13,771 dragonboard_003 INFO: Running ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@10.101.51.13 sudo sync
Warning: Permanently added '10.101.51.13' (ECDSA) to the list of known hosts.
2018-03-21 04:47:14,543 dragonboard_003 INFO: Running snmpset -c private -v1 10.101.48.13 .1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3 i 2
iso.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3 = INTEGER: 2
2018-03-21 04:47:14,661 dragonboard_003 INFO: Running sleep 10
2018-03-21 04:47:24,682 dragonboard_003 INFO: Running snmpset -c private -v1 10.101.48.13 .1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3 i 1
iso.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3 = INTEGER: 1
2018-03-21 04:47:34,811 dragonboard_003 INFO: Checking if master image booted.
2018-03-21 04:47:52,851 dragonboard_003 INFO: Error checking device state. Forcing reboot...
2018-03-21 04:48:02,858 dragonboard_003 INFO: Checking if master image booted.
2018-03-21 04:49:28,297 dragonboard_003 INFO: Flashing Test Image
2018-03-21 04:49:28,715 dragonboard_003 INFO: Running: nc 10.101.50.22 36341| gunzip| sudo dd of=/dev/mmcblk1 bs=16M
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/__init__.py", line 233, in serve_file
    client.send(data)
OSError: [Errno 113] No route to host
2018-03-21 05:19:28,820 dragonboard_003 ERROR: Failed to write image, cleaning up...

2018-03-21 05:19:31,819 dragonboard_003 ERROR: exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1098, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 36341| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 261, in flash_test_image
    self._run_control(cmd, timeout=1800)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 59, in _run_control
    cmd, stderr=subprocess.STDOUT, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 700, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 36341| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 248, in eat
    return self._dispatch()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 298, in _dispatch
    result = ingredient.dispatch(self.context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 152, in dispatch
    return self._dispatch(context, 0)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 165, in _dispatch
    retval = command.invoked(context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/__init__.py", line 44, in invoked
    device.provision()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 374, in provision
    self.flash_test_image(server_ip, server_port)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 263, in flash_test_image
    raise ProvisioningError("timeout reached while flashing image!")
devices.ProvisioningError: timeout reached while flashing image!
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1098, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 36341| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 261, in flash_test_image
    self._run_control(cmd, timeout=1800)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 59, in _run_control
    cmd, stderr=subprocess.STDOUT, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 700, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 36341| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/bin/snappy-device-agent", line 4, in <module>
    __import__('pkg_resources').run_script('snappy-device-agents==0.0.1', 'snappy-device-agent')
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/EGG-INFO/scripts/snappy-device-agent", line 25, in <module>
    main()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/cmd.py", line 75, in main
    Agent().main()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/cmd.py", line 71, in main
    return AgentCommandRecipe(self).main(argv, exit)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/recipes/__init__.py", line 119, in main
    retval = bowl.eat(argv)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 254, in eat
    self._dispatch_failed()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 310, in _dispatch_failed
    ingredient.dispatch_failed(self.context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 248, in eat
    return self._dispatch()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 298, in _dispatch
    result = ingredient.dispatch(self.context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 152, in dispatch
    return self._dispatch(context, 0)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 165, in _dispatch
    retval = command.invoked(context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/__init__.py", line 44, in invoked
    device.provision()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 374, in provision
    self.flash_test_image(server_ip, server_port)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 263, in flash_test_image
    raise ProvisioningError("timeout reached while flashing image!")
devices.ProvisioningError: timeout reached while flashing image!
complete
